default_joint_angles: # The default joint angles for the robot
  0: 0.0
  1: 0.9
  2: 0.0
  3: 0.9
  4: 0.0
  5: 0.9
  6: 0.0
  7: 0.9
  8: -1.5
  9: -1.5
  10: -1.5
  11: -1.5
kp: 20.0 # Proportional gain for the PD controller
kd: 0.5 # Derivative gain for the PD controller
base_init_pos: [0.0, 0.0, 0.42] # Initial position of the robot base
base_init_quat: [1.0, 0.0, 0.0, 0.0] # Initial orientation of the robot base
episode_length_seconds: 20.0 # Length of the episode in seconds
resampling_time_seconds: 4.0 # Time between resampling the action
action_scale: 0.25 # Scale for the action space
simulate_action_latency: true # Whether to simulate action latency
clip_action: 100.0 # Clip the action to a certain range
