default_joint_angles:
  FL_hip_joint: 0.0
  FR_hip_joint: 0.0
  RL_hip_joint: 0.0
  RR_hip_joint: 0.0
  FL_thigh_joint: 0.8
  FR_thigh_joint: 0.8
  RL_thigh_joint: 1.0
  RR_thigh_joint: 1.0
  FL_calf_joint: -1.5
  FR_calf_joint: -1.5
  RL_calf_joint: -1.5
  RR_calf_joint: -1.5
kp: 20.0
kd: 0.5
base_init_pos: [0.0, 0.0, 0.42]
base_init_quat: [1.0, 0.0, 0.0, 0.0]
episode_length_seconds: 20.0
resampling_time_seconds: 4.0
action_scale: 0.25
simulate_action_latency: true
clip_action: 100.0
